# Generated by Django 5.1 on 2024-08-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
