# Generated by Django 5.1 on 2024-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
