# Generated by Django 5.1 on 2024-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_image_auction_listing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='time',
            field=models.TimeField(),
        ),
    ]
