# Generated by Django 5.1 on 2024-08-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
