# Generated by Django 5.1 on 2024-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_listing_alter_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
