# Generated by Django 5.1 on 2024-08-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_listing_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auction_listing',
            new_name='listing',
        ),
    ]
