# Generated by Django 5.1 on 2024-08-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_auction_listing_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
    ]
