# Generated by Django 5.1 on 2024-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
