# Generated by Django 5.1 on 2024-09-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
    ]
