# Generated by Django 5.1 on 2024-09-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_rename_category_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='Category',
        ),
    ]
