# Generated by Django 5.1 on 2024-09-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='auctions.listing'),
        ),
    ]
