# Generated by Django 5.1 on 2024-09-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_winner_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='auctions.listing'),
        ),
    ]
